# Use postgres/example user/password credentials
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword123
      - POSTGRES_DB=myappdb
    ports:
      - "5432:5432"

    volumes:
          - PostgreSQLdb-api-js:/var/lib/postgresql/data # Stockage des données
          - ./db-scripts:/docker-entrypoint-initdb.d/ # Chemin des scripts SQL pour l'initialisation de la base de données

  api:
      build: ./ # Chemin vers le Dockerfile de l'API
      ports:
        - "3000:3000"
      command: npm run dev
      depends_on:
        - db
      environment: # Pour plus de sécurité et n'avoir à les écrire qu'une fois on utilisera .env
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
      volumes:
        - ./src:/app

volumes:
  PostgreSQLdb-api-js: